services:
  db:
    image: mongo
    restart: always
    volumes: 
      - ./mongo-data:/data/db
    expose:
      - 27017
    networks:
      - helter-network
  helter-api:
    image: helter-api
    restart: always
    build:
      context: ./Helter-API
      dockerfile: Dockerfile
    volumes: 
      - ./music:/home/app/music
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
    networks:
      - helter-network
  helter-front:
    image: helter-front
    restart: always
    build:
      context: ./Helter
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - helter-api
    networks:
      - helter-network
networks:
    helter-network:
        driver: bridge
